vrbsp:
	g++ -Wall -std=c++11 -g -o vrbsp_vns vrbsp_vns.cpp

mdvrbsp:
	g++ -D MDVRBSP -std=c++11 mdvrbsp_vns.cpp -o mdvrbsp_vns

vrcheck:
	g++ -std=c++11 -o check feasibility_check.cpp

mdcheck:
	g++ -D MDVRBSP -std=c++11 -o check feasibility_check.cpp
